### ISSUE TITLE
input.sequence.file was missing (ML.CoRa.iter.bpp)

### ISSUE THREAD

**Issue by Xiaojun928** [claudia-c-weber/CoRa#1]
Hi Claudia,

Thanks for sharing the CoRa model.

I want to see if a bacterial population favor CoRa or M0 model, so I tried to run it on several orthologs.  When running CoRa or M0 (for instance `${bpp_basedir}/bppml params=ML.CoRa.iter.bpp DATA=OG0000114`), errors were reported like the below:

```
Parsing options:
Parsing file ML.CoRa.iter.bpp for options.
Random seed set to.....................: 5489
Alphabet type .........................: Codon(letter=DNA)
Genetic Code...........................: Standard
Missing data input.sequence.file option
	from  bpp::BppSequenceApplication::getConstAlignmentsMap
	from  /home-user/software/BioPP/bin//bppml(main+0x3af) [0x7f72f55288bf]
```

The "Missing data input.sequence.file option" exception was thrown due to `!optionalData && mSites.size() == 0)` in [BppSequenceApplication.cpp](https://github.com/BioPP/bpp-seq/blob/35ea699a33974280cedd7e3a3c366a181c9ed558/src/Bpp/Seq/App/BppSequenceApplication.cpp) at line 94. 

The attached file ([OG0000114.fst](https://github.com/claudia-c-weber/CoRa/files/10349513/OG0000114.fst.txt)) was used as input and has been aligned. It should be compatible with `bppml` as it was derived from `clean_buggy_phylip.py`.  Since the format of example data for `bppml` ([lysozymeLarge.fasta](https://github.com/BioPP/bppsuite/blob/master/Examples/Data/lysozymeLarge.fasta)) is similar to mine except that `lysozymeLarge.fasta` contains space between columns of aligned bases, I am not sure if the format is the cause.
Is it possible for you to show me an example of input for `bppml` in your datasets? Thanks in advance.

Kind regards,
Xiaojun

**Comment by claudia-c-weber** [comment]
Hi Xiaojun, 

Thanks for reaching out! Could you confirm which version of bppml you were using, and whether your alignments are in the directory specified in the configuration file (i.e. ./cleaned_fasta/$(DATA).fst)?

As noted in [run_CoRa.sh](https://github.com/claudia-c-weber/CoRa/blob/master/scripts/run_models/run_CoRa.sh), the example was run with Bio++ v. 2.4.0, and the configuration may need to be tweaked slightly to work with 3.0.

Claudia

**Comment by Xiaojun928** [comment]
Hi Claudia,

Thanks for your quick reply. The alignments are in the specified directory. 
Yes, the Bio++ version may be the cause, as the same error occurred when I used the example data ([lysozymeLarge.fasta](https://github.com/BioPP/bppsuite/blob/master/Examples/Data/lysozymeLarge.fasta) and its corresponding treefile) to run CoRa model. 
Now I have installed Bio++ v.2.4.0. which has solved this issue. Thanks again~

Best,
Xiaojun

**Comment by claudia-c-weber** [comment]
Hi Xiaojun,

Thanks for confirming! I've added a note about the version to the readme.

Claudia

**Comment by Xiaojun928** [comment]
Hi Claudia,

I want to see if the CoRa model fit better for a bacterial population with small Ne (~10^7). So I tried to implement your scripts  on my datasets (38 closely related strains, affiliated with teh same genus). At first, I tried three single-copy orthologs, everything goes well until running CoRa and M0 model.
In this step, both *M0.params.txt and *Cora.params.txt only contain `Log likelihood` and `Number of sites`, while other results required by `parse_CoRa.py` were not generated. I checked the log file, there are some warnings like below, and no additional error was reported.

```
WARNING!!! Branch length 15 is too small: 5e-07. Value is set to 1e-06
...
WARNING!!! Branch length 23 is too small: 3.90703e-17. Value is set to 1e-06
...
WARNING!!! Branch length 67 is too small: 5e-07. Value is set to 1e-06
......
WARNING!!! This parameter has a value close to the boundary: BrLen18(1e-06).
...
...
WARNING!!! This parameter has a value close to the boundary: BrLen125(1e-06).
WARNING!!! Parameter output.estimates.alias not specified. Default used instead: 1
```

I guess incomplete results may be caused by the too short branch length (< 1e-06). So I tried run model fitting on a group of more distantly related strains (111 strains from different bacteria genera). However, the problem still exists (i.e, short branch length, incomplete output of *params.txt). I was wondering if this method could only be applied for distanly related taxa, e.g., with branch length > 1e-06. If yes, I may not apply it to datasets at poplation level. Please correct me if I am wrong. Many thanks for your help!

I attached my inputs and output (of the more distantly related ) for model fitting in case you may look at. 
[Example.tar.gz](https://github.com/claudia-c-weber/CoRa/files/10383669/Example.tar.gz)


Best regards,
Xiaojun

**Comment by gavinmdouglas** [comment]
Hey @Xiaojun928 -- if you're still interested in running this tool then take a look at this issue I just opened which is very relevant: https://github.com/claudia-c-weber/CoRa/issues/2

**Comment by claudia-c-weber** [comment]
Hi Xiaojun,

@gavinmdouglas has correctly identified that the version of bpp-phyl used for the benchmarks was a few commits ahead of the tagged version. Please see the updated Readme.

Having said that, if you are frequently seeing warnings about short branches, codon models may not be suitable for what you are trying to do. You might be capturing segregating variation rather than fixed differences, for example. See this paper for a discussion on potential biases in omega estimates as they relate to distances between sequences: https://doi.org/10.1534/genetics.113.152025

Claudia
