### ISSUE TITLE
CodonAAClustFreq model missing in Bio++ releases

### ISSUE THREAD

**Issue by gavinmdouglas** [claudia-c-weber/CoRa#2]
Hey @claudia-c-weber,

Thanks for developing this approach!

I was troubleshooting the same problem reported in this other issue: https://github.com/claudia-c-weber/CoRa/issues/1#issuecomment-1377397579 (not the initial issue, but that nothing was found in the output with Bio++ v2.4.0 and your example commands).

After looking into more I realized that confusingly "AAClust" is not actually defined anywhere in the released versions of Bio-Phyl v2.4.0 or v2.4.1, but that it is here in the most recent developmental version: https://github.com/BioPP/bpp-phyl/blob/368c195dc23fd121d66dc163f4bdb0aac46c8f4f/src/Bpp/Phyl/Io/BppOSubstitutionModelFormat.cpp#L1270 . It seems like the bbpml just defaults to using "Codon" or "CodonFreq" as the option if "AAClust" cannot be found. It seems like there should be a check there to see if an intended model option does not actually exist. I also confirmed that the string "AAClust" does not occur anywhere in the rest of the Bio++ v2.4.0/v2.4.1 codebases for Bpp-phyl, bpp-core, bpp-popgen, bpp-seq, or bppsuite.

I'm wondering if perhaps you ran your tests with the developmental version of Bio++, which had this model defined, but that it for some reason did not make it into the actual released versions? If so, referring users to a specific commit of the developmental branch to use, rather than a version number, would be better.

Anyway, I believe I have it working with the latest Bio++ development version now (v3), although it requires different parameters (and rather than `params=...` it's `param=...) - see below.

In the new param file (`ML.CoRa.iter.v3.bpp`) I placed:
```
MODEL = CoRa
OUTDIR = ./output/

alphabet=Codon(letter=DNA)
genetic_code=Standard

input.data1 = alignment(file=./cleaned_fasta/$(DATA).fst)
input.tree1 = user(file=./bionj/$(DATA).AA.bionj.dnd, format=Newick)
model1 = CodonAAClustFreq(model=K80(),frequencies=F3X4)
process1 = Homogeneous(tree=1, model=1)
phylo1 = Single(data=1, process=1)

output.infos = $(OUTDIR)$(DATA).$(MODEL).infos
output.estimates = $(OUTDIR)$(DATA).$(MODEL).params.txt
output.tree.file = $(OUTDIR)$(DATA).$(MODEL).tre
```

I then ran (similar to the command in `run_CoRa.sh`):

```
mkdir output
${bpp_basedir}/bppml param=ML.CoRa.iter.v3.bpp DATA="${f}"
```

I'm a novice with Bpp, so I'm unsure whether these options match exactly how you ran it previously, but I think it's quite similar. Any suggestions or comments would be great though!

**Comment by claudia-c-weber** [comment]
Hi Gavin,

Thank you pointing this out.

The commit introducing the functionality was actually made to the main branch of bpp-phyl a few days after v.2.4.1 was tagged. See here: https://github.com/BioPP/bpp-phyl/commit/64b6abc67d815ca062a90ed4390d457c83dc534b I will add a note to the instructions to make this clear.

The developers of Bio++ are very helpful, so you could raise the issue about the missing check with them.

Regarding your configuration file, the key line is `model1 = CodonAAClustFreq(model=K80(),frequencies=F3X4)`, and you're applying a single homogeneous process over the tree, so the structure should be broadly correct.

As Laurent Guéguen, who added the model to the library, explained:

> model=K80()" means that there is one basic nucleotidic model, K80,
> with only parameter kappa, and "Freq" means that equilibrium
> frequencies are defined in the description of the model

> To define specific clusters, there is argument "partition". The
> default is "partition=(1,2,3,3,3,2,2,1,2,4,4,2,4,4,1,3,3,2,2,1)", as
> in CoRa.

As for the finer details: The settings provided in the configuration file in this repo were chosen to be as close as possible to those used in ModelOMatic (no longer maintained) for the original experiments in the paper. That would include things like the optimization tolerance. At some point, the results for M0 would also have been compared to output from codeml. If you wanted to confirm that your updated configuration produces similar results, you could consider checking out the above-mentioned commit and comparing a few alignments.

I hope that helps,

Claudia
